# Generated by Django 4.0.6 on 2022-08-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('AP', 'Appetizers'), ('SP', 'Soups'), ('SL', 'Salads'), ('DS', 'Desserts'), ('DR', 'Drinks'), ('OT', 'Other')], default='OT', max_length=25),
        ),
    ]
